Set GOROOT
GOROOT was dropped by https://github.com/actions/setup-go/pull/175.

If it is not set then this test fails with:

    --- FAIL: TestGVMRunUse (5.45s)
    --- FAIL: TestGVMRunUse/1.7.4_bash (2.68s)
        use_test.go:54: export GOROOT="/home/runner/.gvm/versions/go1.7.4.linux.amd64"
            export PATH="/home/runner/.gvm/versions/go1.7.4.linux.amd64/bin:$PATH"

        use_test.go:79: failed to run go version: exit status 2
            go: cannot find GOROOT directory: /usr/local/go